#
# Use this dockerfile to run apigility in dev mode.
#
# Start the dev server using docker-compose:
#
#   docker-compose build
#   docker-compose up
#
# OR use plain old docker 
#
#   docker build -f Dockerfile-dev -t apigility-dev .
#   docker run -it -p "8080:80" -v $PWD:/var/www apigility-dev
#
FROM php:5.6-apache

RUN apt-get update \
 && DEBIAN_FRONTEND=noninteractive apt-get install git zlib1g-dev nano -y --no-install-recommends \
 && rm -r /var/lib/apt/lists/* \
 && docker-php-ext-install zip pdo_mysql \
 && curl -sS https://getcomposer.org/installer \
  | php -- --install-dir=/usr/local/bin --filename=composer \
 && a2enmod rewrite \
 && sed -i 's!/var/www/html!/var/www/public!g' /etc/apache2/apache2.conf \
 && echo "AllowEncodedSlashes On" >> /etc/apache2/apache2.conf \
 && mv /var/www/html /var/www/public \
 && cp /usr/src/php/php.ini-production /usr/local/etc/php/php.ini \
 && printf '[Date]\ndate.timezone=UTC' > /usr/local/etc/php/conf.d/timezone.ini

COPY docker-entrypoint.sh /usr/local/bin
RUN ln -s /usr/local/bin/docker-entrypoint.sh /entrypoint.sh # backwards compat
RUN chmod 755 /usr/local/bin/docker-entrypoint.sh

WORKDIR /var/www

VOLUME /var/www

RUN cp /usr/src/php/php.ini-development /usr/local/etc/php/php.ini

ENTRYPOINT ["docker-entrypoint.sh"]

#CMD php -S 0.0.0.0:80 -t public public/index.php
