#
# Use this dockerfile to run apigility in dev mode.
#
# Start the dev server using docker-compose:
#
#   docker-compose build
#   docker-compose up
#
# OR use plain old docker 
#
#   docker build -f Dockerfile-dev -t apigility-dev .
#   docker run -it -p "8080:80" -v $PWD:/var/www apigility-dev
#
FROM php:7.0-apache

RUN apt-get update \
 && DEBIAN_FRONTEND=noninteractive apt-get install git zlib1g-dev nano -y --no-install-recommends mysql-server \
 && rm -r /var/lib/apt/lists/* \
 && docker-php-ext-install zip pdo_mysql \
 && curl -sS https://getcomposer.org/installer \
  | php -- --install-dir=/usr/local/bin --filename=composer \
 && a2enmod rewrite \
 && sed -i 's!/var/www/html!/var/www/public!g' /etc/apache2/apache2.conf \
 && echo "AllowEncodedSlashes On" >> /etc/apache2/apache2.conf \
 && mv /var/www/html /var/www/public \
 && cp /usr/src/php/php.ini-production /usr/local/etc/php/php.ini \
 && printf '[Date]\ndate.timezone=UTC' > /usr/local/etc/php/conf.d/timezone.ini

WORKDIR /var/www
### END OF Dockerfile copy

VOLUME /var/www

RUN cp /usr/src/php/php.ini-development /usr/local/etc/php/php.ini

CMD composer install \
 && php public/index.php development enable \
 && /etc/init.d/mysql start \
 && ./vendor/bin/phing reset-db \
 && ./vendor/bin/phing setup \
 && php -S 0.0.0.0:80 -t public public/index.php

